name: Build on Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        uses: Joshua-Ashton/arch-mingw-github-action@9cdb815264bce7a6346927521b176f578982679d
        with:
          command: |
            ./package-release.sh master build

      - name: Create tarball
        run: tar cvfz "fakenvapi.tar.gz" -C "./build/fakenvapi-master" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fakenvapi-${{ github.ref_name }}
          path: build/fakenvapi-master
