name: Build on Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: Joshua-Ashton/arch-mingw-github-action@9cdb815264bce7a6346927521b176f578982679d
        with:
          command: |
            ./package-release.sh master build

      - name: Create tarball
        run: tar cvfz "nvapi-dummy.tar.gz" -C "./build/nvapi-dummy-master" .
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-nvapi-master
          path: build/nvapi-dummy-master
